# Generated by Django 2.1.1 on 2018-09-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('month', models.CharField(max_length=10)),
                ('day', models.IntegerField()),
                ('min', models.IntegerField()),
                ('year', models.IntegerField()),
                ('retweet', models.IntegerField()),
                ('favorite', models.IntegerField()),
                ('img', models.TextField(max_length=500)),
            ],
        ),
    ]
