# Generated by Django 2.1.1 on 2018-09-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180926_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='min',
            field=models.CharField(max_length=300),
        ),
    ]
