# Generated by Django 2.1.1 on 2018-09-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180926_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='hour',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='min',
            field=models.IntegerField(default=59),
        ),
    ]
