# Generated by Django 2.1.1 on 2018-09-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180926_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='hour',
            field=models.CharField(default='hour', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='location',
            field=models.CharField(default='location', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='month',
            field=models.CharField(default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='name', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='text', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='type',
            field=models.CharField(default='type', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='username', max_length=300),
        ),
    ]
