# Generated by Django 2.1.1 on 2018-09-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180926_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.CharField(default='day', max_length=300),
        ),
    ]
