# Generated by Django 2.1.1 on 2018-09-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tweet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='bg',
            field=models.TextField(default='bg', max_length=500),
        ),
        migrations.AddField(
            model_name='tweet',
            name='url',
            field=models.TextField(default='url', max_length=500),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.TextField(default='img', max_length=500),
        ),
    ]
