# Generated by Django 2.1.1 on 2018-09-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180927_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='url',
        ),
    ]
