# Generated by Django 2.1.1 on 2018-09-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180927_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='bg',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
