# Generated by Django 2.1.1 on 2018-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180927_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='bg',
            field=models.URLField(default='https://www.cbronline.com/wp-content/uploads/2016/06/twitter2.png', max_length=500),
        ),
    ]
