# Generated by Django 2.1.1 on 2018-09-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180927_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='bg',
        ),
    ]
