# Generated by Django 2.1.1 on 2018-09-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tweet_bg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='bg',
            new_name='background',
        ),
    ]
