# Generated by Django 2.1.1 on 2018-10-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20181026_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
