# Generated by Django 2.1.1 on 2018-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20181029_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='background',
            field=models.URLField(blank=True, default='https://www.cbronline.com/wp-content/uploads/2016/06/twitter2.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.CharField(blank=True, default='day', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='day',
            field=models.CharField(blank=True, default='day', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='favorite',
            field=models.CharField(blank=True, default='favorite', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hour',
            field=models.CharField(blank=True, default='hour', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.URLField(blank=True, default='https://yt3.ggpht.com/a-/AN66SAyn4D2lHHaONid5n_y_ZIsyInEUOoktizKFew=s900-mo-c-c0xffffffff-rj-k-no', max_length=500),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='location',
            field=models.CharField(blank=True, default='location', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='min',
            field=models.CharField(blank=True, default='min', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='month',
            field=models.CharField(blank=True, default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(blank=True, default='name', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet',
            field=models.CharField(blank=True, default='retweet', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(blank=True, default='text', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='type',
            field=models.CharField(blank=True, default='type', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(blank=True, default='username', max_length=300),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='year',
            field=models.CharField(blank=True, default='year', max_length=300),
        ),
    ]
